name: dart_notification_center
description: A wrapper for the observer pattern for Dart in the style of the iOS Notification Center.
version: 1.0.1
homepage: https://github.com/leanhdaoit

environment:
  sdk: ">=2.12.0 <3.0.0"
